#!/usr/bin/env node
/**
 * Package the Web2cmd server as a single Windows .exe (Node SEA).
 *
 * Pipeline:
 *   1. esbuild-bundle the server (sea-entry.js) into one CJS file, with node-pty kept external
 *      (it's a native addon — it can't be bundled; it's extracted at runtime instead).
 *   2. Stage the runtime payload: the web build, the win32-x64 node-pty package, and the Claude
 *      fence hook. The SEA bootstrap extracts these on first run (see sea-bootstrap.ts).
 *   3. Write a manifest + sea-config.json that lists every payload file as a SEA asset.
 *   4. Generate the SEA blob (`node --experimental-sea-config`).
 *   5. Copy node.exe → web2cmd.exe and inject the blob with `postject`.
 *
 * Steps 1–3 (and a runnable bundle) work fully offline. Step 5 needs `postject`
 * (`npm i -g postject` or `npx postject`), which requires network the first time.
 *
 *   node scripts/build-exe.mjs              # full pipeline (needs postject for the final step)
 *   node scripts/build-exe.mjs --stage-only # bundle + stage + manifest only (no SEA)
 */
import { createRequire } from "node:module";
import { execFileSync } from "node:child_process";
import { cpSync, existsSync, mkdirSync, readdirSync, readFileSync, rmSync, statSync, writeFileSync } from "node:fs";
import { dirname, join, relative, resolve } from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";

const require = createRequire(import.meta.url);
const root = resolve(dirname(fileURLToPath(import.meta.url)), "..");

// esbuild is a (nested) transitive dep under pnpm, not hoisted to the workspace root — resolve it
// straight out of the .pnpm store rather than relying on bare-specifier resolution.
async function loadEsbuild() {
  const pnpm = join(root, "node_modules", ".pnpm");
  const cand = readdirSync(pnpm).filter((d) => /^esbuild@/.test(d)).sort().reverse();
  for (const c of cand) {
    const main = join(pnpm, c, "node_modules", "esbuild", "lib", "main.js");
    if (existsSync(main)) {
      const mod = await import(pathToFileURL(main).href);
      return (mod.default ?? mod).build;
    }
  }
  throw new Error("could not locate esbuild in node_modules/.pnpm");
}
const build = await loadEsbuild();
const out = join(root, "build", "exe");
const stage = join(out, "stage");
const stageOnly = process.argv.includes("--stage-only");

const log = (m) => console.log(`[build-exe] ${m}`);
const p = (...s) => join(...s); // shorthand

// ---- 0. clean ----
rmSync(out, { recursive: true, force: true });
mkdirSync(stage, { recursive: true });

// ---- 1. esbuild bundle ----
log("bundling server (node-pty external)…");
await build({
  entryPoints: [join(root, "server", "dist", "sea-entry.js")],
  bundle: true,
  platform: "node",
  format: "cjs",
  target: "node20",
  outfile: join(out, "server.cjs"),
  external: ["node-pty"], // native addon — extracted + required at runtime
  // CJS has no import.meta; shim import.meta.url to the bundle's own file URL so createRequire()
  // and fileURLToPath() keep working (node-pty still resolves via NODE_PATH set by the bootstrap).
  define: { "import.meta.url": "importMetaUrl" },
  banner: {
    js:
      "// Web2cmd packaged server bundle — generated by scripts/build-exe.mjs\n" +
      'const importMetaUrl = require("url").pathToFileURL(__filename).href;',
  },
  logLevel: "warning",
});

// ---- 2. stage the runtime payload ----
log("staging payload (web dist + node-pty win32-x64 + fence hook)…");
function findPty() {
  const pnpm = join(root, "node_modules", ".pnpm");
  const dir = readdirSync(pnpm).find((d) => /^node-pty@/.test(d));
  if (!dir) throw new Error("node-pty not found in node_modules/.pnpm");
  return join(pnpm, dir, "node_modules", "node-pty");
}
const ptyDir = findPty();
const ptyDest = p(stage, "node_modules", "node-pty");
mkdirSync(ptyDest, { recursive: true });
cpSync(p(ptyDir, "package.json"), p(ptyDest, "package.json"));
cpSync(p(ptyDir, "lib"), p(ptyDest, "lib"), { recursive: true });
cpSync(p(ptyDir, "prebuilds", "win32-x64"), p(ptyDest, "prebuilds", "win32-x64"), { recursive: true });

const webDist = p(root, "web", "dist");
if (!existsSync(webDist)) throw new Error("web/dist not found — run `pnpm --filter @web2cmd/web build` first");
cpSync(webDist, p(stage, "web", "dist"), { recursive: true });

mkdirSync(p(stage, "scripts"), { recursive: true });
cpSync(p(root, "scripts", "fence-hook.mjs"), p(stage, "scripts", "fence-hook.mjs"));

// ---- 3. manifest + sea-config ----
function walk(dir) {
  const files = [];
  for (const e of readdirSync(dir, { withFileTypes: true })) {
    const full = p(dir, e.name);
    if (e.isDirectory()) files.push(...walk(full));
    else files.push(full);
  }
  return files;
}
const version = JSON.parse(readFileSync(p(root, "server", "package.json"), "utf8")).version;
const stagedFiles = walk(stage).map((f) => relative(stage, f).split("\\").join("/"));
const manifest = { version, files: stagedFiles };
const manifestPath = p(out, "manifest.json");
writeFileSync(manifestPath, JSON.stringify(manifest));

const assets = { "manifest.json": manifestPath };
for (const rel of stagedFiles) assets[rel] = p(stage, rel.split("/").join("\\"));

const seaConfig = {
  main: p(out, "server.cjs"),
  output: p(out, "sea-prep.blob"),
  disableExperimentalSEAWarning: true,
  assets,
};
const seaConfigPath = p(out, "sea-config.json");
writeFileSync(seaConfigPath, JSON.stringify(seaConfig, null, 2));
log(`staged ${stagedFiles.length} payload files; bundle + manifest + sea-config written to build/exe/`);

const totalBytes = walk(stage).reduce((n, f) => n + statSync(f).size, 0);
log(`payload size ≈ ${(totalBytes / 1024 / 1024).toFixed(1)} MB`);

if (stageOnly) {
  log("--stage-only: done. To test the bundle without SEA:");
  log(`  $env:NODE_PATH="${p(stage, "node_modules")}"; $env:WEB2CMD_WEB_DIST="${p(stage, "web", "dist")}"; node "${p(out, "server.cjs")}"`);
  process.exit(0);
}

// ---- 4. SEA blob ----
log("generating SEA blob…");
execFileSync(process.execPath, ["--experimental-sea-config", seaConfigPath], { stdio: "inherit" });

// ---- 5. copy node.exe + inject blob via postject ----
const exePath = p(out, "web2cmd.exe");
cpSync(process.execPath, exePath);
log(`copied node runtime → ${exePath}`);
try {
  log("injecting blob with postject…");
  execFileSync(
    "npx",
    ["--yes", "postject", exePath, "NODE_SEA_BLOB", p(out, "sea-prep.blob"), "--sentinel-fuse", "NODE_SEA_FUSE_fce680ab2cc467b6e072b8b5df1996b2"],
    { stdio: "inherit", shell: true },
  );
  log(`DONE → ${exePath}`);
} catch (e) {
  log("postject step failed (needs network/postject). Bundle, payload, blob and sea-config are ready.");
  log("Finish on a machine with postject:");
  log(`  npx postject "${exePath}" NODE_SEA_BLOB "${p(out, "sea-prep.blob")}" --sentinel-fuse NODE_SEA_FUSE_fce680ab2cc467b6e072b8b5df1996b2`);
  process.exit(1);
}
